Direct Linear Solvers for Symmetric Positive Definite Toeplitz Matrices
JuliaLinearAlgebra/ToeplitzMatrices.jl pull request #64
Opened 2022-01-04 10:00 UTC by SebastianAment

# Overview 
This PR adds implementations of the Durbin and Levinson algorithms that improve on the performance of StatsBase's implementation by a factor of two for larger matrices. The performance advantage starts to appear before `n = 32` and grow with `n`. Experiments were run on a 2021 MacBook Pro with an M1 Pro.

Since this package specializes on Toeplitz matrices, I think the implementations are better incorporated here than at StatsBase. Further, this PR also adds Trench's algorithm for the efficient inversion of symmetric positive definite Toeplitz matrices. See below for performance benchmarks.

For a reference, see [Golub and Van Loan, page 208.](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwititz36pf1AhXckIkEHWYPAiQQFnoECAUQAQ&url=http%3A%2F%2Fmath.ecnu.edu.cn%2F~jypan%2FTeaching%2Fbooks%2F2013%2520Matrix%2520Computations%25204th.pdf&usg=AOvVaw26GX7osGTu7etg5RSyfh-P)

# Benchmarks

## Durbin
### `n = 4096`
```
durbin
  5.571 ms (2 allocations: 32.05 KiB)
durbin!
  5.568 ms (0 allocations: 0 bytes)
StatsBase.durbin
  11.043 ms (2 allocations: 32.05 KiB)
StatsBase.durbin!
  11.041 ms (0 allocations: 0 bytes)
canonical solve
  161.529 ms (8 allocations: 128.09 MiB)
```

### `n = 32`
```
durbin
  716.241 ns (1 allocation: 336 bytes)
durbin!
  646.341 ns (0 allocations: 0 bytes)
StatsBase.durbin
  818.494 ns (1 allocation: 336 bytes)
StatsBase.durbin!
  794.708 ns (0 allocations: 0 bytes)
canonical solve
  54.375 μs (4 allocations: 9.11 KiB)
```

## Levinson
### `n = 4096`
```
levinson
  9.533 ms (4 allocations: 64.09 KiB)
levinson!
  9.531 ms (2 allocations: 32.05 KiB)
StatsBase.levinson
  23.107 ms (4 allocations: 64.09 KiB)
StatsBase.levinson!
  23.110 ms (0 allocations: 0 bytes)
canonical solve
  161.600 ms (6 allocations: 128.06 MiB)
```

### `n = 32`
```
levinson
  905.273 ns (2 allocations: 672 bytes)
levinson!
  897.925 ns (1 allocation: 336 bytes)
StatsBase.levinson
  1.221 μs (2 allocations: 672 bytes)
StatsBase.levinson!
  1.175 μs (0 allocations: 0 bytes)
direct solve
  52.750 μs (3 allocations: 8.78 KiB)
```

## Trench 
### `n = 4096`
```
trench
  18.469 ms (14 allocations: 128.06 MiB)
canonical inv
  499.677 ms (6 allocations: 130.03 MiB)
```
### `n = 32`
```
trench
  1.279 μs (7 allocations: 8.94 KiB)
canonical inv
  59.542 μs (4 allocations: 24.58 KiB)
```

2022-01-04 10:12 UTC, SebastianAment commented
Further notes:

- `StatsBase.levinson!` mutates `b`, which is unexpected (and should probably be called `levinson!!`).  For this reason, the new `levinson!` implementation still allocates a single vector of length `n`.
-  If the current maintainers want to incorporate the new implementations, I'd also change lines 687 to 701 to use the new `levinson` implementation.
- We could also add a `SymmetricPositiveDefiniteToeplitz` type, for which `inv` and `\` automatically call `trench` and `levinson`, respectively.

2022-01-16 21:35 UTC, dlfivefifty requested changes

2022-01-16 21:35 UTC, dlfivefifty commented on src/directLinearSolvers.jl
> +    α, β = -r[1], 1
Does the `1` cause a type instability?

2022-01-16 21:35 UTC, dlfivefifty commented on src/directLinearSolvers.jl
> +    if r_0 != 1 # levinson implementation assumes normalization of diagonal
`!isone(r_0)` may be more general

2022-01-16 21:35 UTC, dlfivefifty commented on src/directLinearSolvers.jl
> +    if r_0 != 1
ditto

2022-01-16 21:35 UTC, dlfivefifty commented on src/directLinearSolvers.jl
> +    α, β = -r[1], 1
ditto

2022-01-16 21:35 UTC, dlfivefifty commented on src/directLinearSolvers.jl
> +    if r_0 != 1 # levinson implementation assumes normalization of diagonal
ditto

2022-01-16 21:35 UTC, dlfivefifty commented on src/directLinearSolvers.jl
> +    if r_0 != 1
ditto

2022-01-16 21:35 UTC, dlfivefifty commented on test/runtests.jl
> +    end
add tests for type stability (`@inferred`).

2022-01-16 22:57 UTC, dlfivefifty commented
> * We could also add a `SymmetricPositiveDefiniteToeplitz`

Not a good idea: there’s no equivalent in LinearAlgebra. The analogue there is explicitly calling `  cholesky  `

2022-01-17 09:10 UTC, SebastianAment commented
> > * We could also add a `SymmetricPositiveDefiniteToeplitz`
> 
> Not a good idea: there’s no equivalent in LinearAlgebra. The analogue there is explicitly calling ` cholesky`

This is not central to this PR, just adding my thoughts: 

- There are the `Symmetric` and `Hermitian` wrappers in LinearAlgebra which do impact how `factorize` behaves. There's no clear reason in my mind why one property should be dispatched on, while the other one shouldn't. In the case of Toeplitz matrices, checking definiteness is also an O(n^2) operation, same as checking symmetry for regular matrices.
- Signaling positive definiteness via types would make it easier to write generic code that should work efficiently for both definite and indefinite systems. 
- It would be easier for non-experts (i.e. people who have not heard of Trench's or Levinson's algorithms) to take advantage of the efficient solver and inversion algorithms by just turning on a flag. This could be done by having a `PositiveDefinite` trait as a field in the `SymmetricToeplitz` structure.

2022-03-25 13:36 UTC, dkarrasch reviewed
I found a few minor style issues.

2022-03-25 13:36 UTC, dkarrasch commented on src/directLinearSolvers.jl
> +computes `y = T \\ (-r)` where T = SymmetricToeplitz(vcat(1, r[1:end-1])).
```suggestion
    durbin(r::AbstractVector)

Computes `y = T \\ (-r)` where `T = SymmetricToeplitz(vcat(1, r[1:end-1]))`.
```

2022-03-25 13:36 UTC, dkarrasch commented on src/directLinearSolvers.jl
> +```
```suggestion

    durbin!(y::AbstractVector, r::AbstractVector)

```

2022-03-25 13:36 UTC, dkarrasch commented on src/directLinearSolvers.jl
> +```
```suggestion

    trench(T::SymmetricToeplitz)

```

2022-03-25 13:36 UTC, dkarrasch commented on src/directLinearSolvers.jl
> +    n = checksquare(T)
```suggestion
    n = length(T.vc)
```

2022-03-25 13:36 UTC, dkarrasch commented on src/directLinearSolvers.jl
> +    n = checksquare(B)
```suggestion
    n = LinearAlgebra.checksquare(B)
```

When resolving the merge conflict, I might have removed the import of `checksquare`...

2022-03-25 13:36 UTC, dkarrasch commented on src/directLinearSolvers.jl
> +solves `x = T \\ b where T = SymmetricToeplitz(vcat(1, r)), i.e. T_{ij} = r[abs(i-j)]`` where by assumption `r[0] = 1` and `T` is positive definite.
```suggestion

    levinson(r::AbstractVector, b::AbstractVector)

solves `x = T \\ b` where `T = SymmetricToeplitz(vcat(1, r))`, i.e. `T_{ij} = r[abs(i-j)]`
where by assumption `r[0] = 1` and `T` is positive definite.
```

2022-03-25 13:36 UTC, dkarrasch commented on src/directLinearSolvers.jl
> +same as `levinson`, but uses the pre-allocated vector `x` to store the result.
```suggestion

    levinson!(x::AbstractVector, r::AbstractVector, b::AbstractVector, y::AbstractVector = zero(x))

Same as `levinson`, but uses the pre-allocated vector `x` to store the result.
```

2022-03-29 11:29 UTC, SebastianAment commented
> I found a few minor style issues.

I just committed your suggestions.

2022-09-07 00:26 UTC, ParadaCarleton commented
Is anything holding this up? @dkarrasch @SebastianAment

2022-09-07 08:41 UTC, dlfivefifty approved these changes

2022-09-12 10:57 UTC, dkarrasch reviewed
A few more style suggestions.

2022-09-12 10:57 UTC, dkarrasch commented on src/directLinearSolvers.jl
> +
```suggestion

```

2022-09-12 10:57 UTC, dkarrasch commented on src/directLinearSolvers.jl
> +
```suggestion

```

2022-09-12 10:57 UTC, dkarrasch commented on src/directLinearSolvers.jl
> +```
```suggestion
    trench!(B::AbstractMatrix, T::SymmetricToeplitz)

```

2022-09-12 10:57 UTC, dkarrasch commented on src/directLinearSolvers.jl
> +of T and returns a `Symmetric` wrapper of `B`.
```suggestion
of `T` and returns a `Symmetric` wrapper of `B`.
```

2022-09-12 10:57 UTC, dkarrasch commented on src/directLinearSolvers.jl
> +solves `x = T \\ b` where `T = SymmetricToeplitz(vcat(1, r))`, i.e. `T_{ij} = r[abs(i-j)]`
```suggestion
    levinson(r::AbstractVector, b::AbstractVector)

Solves `x = T \\ b` where `T = SymmetricToeplitz(vcat(1, r))`, i.e. `T_{ij} = r[abs(i-j)]`
```

2022-09-12 10:57 UTC, dkarrasch commented on src/directLinearSolvers.jl
> +
```suggestion

```

2022-09-12 11:00 UTC, dkarrasch commented
Out of curiosity, why not make the overloaded functions available in `StatsBase.jl`? Do you need special fields of structs that are owned by this package here?

2022-09-14 16:24 UTC, ParadaCarleton commented
@dkarrasch if the only thing missing is a couple style changes, perhaps we should just apply the changes and merge, to avoid holding this up too long?

2022-09-14 17:01 UTC, dkarrasch commented
> Out of curiosity, why not make the overloaded functions available in `StatsBase.jl`? Do you need special fields of structs that are owned by this package here?

I still wonder... There will be `durbin` methods and others both in `StatsBase.jl` and here. How will people judge which one to use? The backend appears to be fairly generic.

2022-09-14 18:06 UTC, ParadaCarleton commented
> > Out of curiosity, why not make the overloaded functions available in `StatsBase.jl`? Do you need special fields of structs that are owned by this package here?
> 
> I still wonder... There will be `durbin` methods and others both in `StatsBase.jl` and here. How will people judge which one to use? The backend appears to be fairly generic.

I do think the best approach is to dispatch on the most efficient function for a given matrix, as @SebastianAment suggested.

2022-09-14 18:07 UTC, ParadaCarleton commented
> > Out of curiosity, why not make the overloaded functions available in `StatsBase.jl`? Do you need special fields of structs that are owned by this package here?
> 
> I still wonder... There will be `durbin` methods and others both in `StatsBase.jl` and here. How will people judge which one to use? The backend appears to be fairly generic.

Presumably they will be, but that would require a PR in StatsBase.jl.

2023-02-07 20:23 UTC, ParadaCarleton commented
@dlfivefifty could you merge this?

2023-02-26 21:10 UTC, merged